version: '2'
services:
  base: &base
    image: ruby:2.4.0
    working_dir: /home/app/mercy
    volumes:
      - .:/home/app/mercy
      - mercy_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  mercy:
    <<: *base
    container_name: mercy
    command: /bin/bash -c 'bundle install && bundle exec rspec'

volumes:
  mercy_gems_2_4_0:
